export const nomineesOptions = [
  "Basher Ali Shihab Thangal",
  "PK Abdurabb",
  "PK Basheer",
  "KPA Majeed",
  "PK Moosa Alias Balathil Baapu",
  "Malakathil Soopy",
  "K Muhammed Unni Haji",
  "Prof KM Aboobacker",
  "Hashim V",
  "ET Muhammed Basheer",
  "KPS Kunhava Thangal",
  "MPM Ishaque Kurikkal",
  "Abdul Muhaimin Alungal",
  "Dr VP Abdul Hameed",
  "Akbar KM",
  "Ashique PK",
  "CP Suhail",
  "Farook",
];
