export const nomineesOptions = [
  "Basher Ali Shihab Thangal",
  "PK Abdurabb",
  "PK Basheer MLA",
  "KPA Majeed MLA",
  "PK Moosa Alias Balathil Baapu",
  "Nalakath Soopy",
  "K Muhammed Unni Haji",
  "Prof KM Aboobacker",
  "Hashim V",
  "ET Muhammed Basheer",
  "KPS Kunhava Thangal",
  "MPM Ishaque Kurikkal",
  "Abdul Muhaimin Alungal",
  "Dr VP Abdul Hameed",
  "Akbar KM",
  "Ashique PK",
  "CP Suhail",
  "Farook",
];
